name: Awesome Shop
on: 
  push:
    branches: [main]
    paths-ignore:
      - '**/README.md'

jobs:
  Unit_Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.0'
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
      