name: Awesome Shop
on: 
  push:
    branches: [main]
    paths-ignore:
      - '**/README.md'

jobs:
  Unit_Test:
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: "11.0"
      FLUTTER_VERSION: "2.10.0"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: $JAVA_VERSION
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: $
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
      